# Generated by Django 3.2.5 on 2021-07-11 03:39

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data',
            field=django_cryptography.fields.encrypt(models.BinaryField(unique=True)),
        ),
    ]
