language: python

python:
- "3.8"

env:
- DJANGO=3.2.5

install:
- pip install -r requirements.txt

before_script:
- python GiftcardSite/manage.py makemigrations LegacySite
- python GiftcardSite/manage.py migrate
- ./GiftcardSite/import_dbs.sh

script:
- python src/manage.py test 

